project_id = "mtcthkzvpfctjanehgdr"

[functions.payments-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.create-reseller-checkout]
verify_jwt = false

[functions.get-stripe-price]
verify_jwt = false

[functions.verify-checkout-session]
verify_jwt = false

[functions.create-submission-invoice]
verify_jwt = false
