#!/usr/bin/env bash
# Re-mirror React Router v7 docs into docs/react-router-v7/.
#
# Idempotent: re-runs overwrite docs/react-router-v7/* cleanly.
#
# ─────────────────────────────────────────────────────────────
# TODO: regenerate reference.md from inside a Claude Code session.
# The context7 dump (docs/react-router-v7/reference.md) MUST be
# regenerated via Claude Code MCP — run from agent context, not
# standalone shell. This script handles only the curl pages +
# date stamp. To refresh reference.md:
#   1. From a Claude Code session, invoke:
#      mcp__context7__resolve-library-id  libraryName="React Router"
#   2. Then mcp__context7__query-docs against /remix-run/react-router/<latest-tag>
#      with a broad framework-mode query (tokenBudget ≥ 50000).
#   3. Save concatenated output to docs/react-router-v7/reference.md.
# ─────────────────────────────────────────────────────────────

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$REPO_ROOT/docs/react-router-v7"
RAW_BASE="https://raw.githubusercontent.com/remix-run/react-router/main/docs"

mkdir -p "$OUT"

# Curated list of paths under docs/ in remix-run/react-router.
# Filenames mirror GitHub paths with `/` → `__`.
files=(
  # Framework mode start pages (PRIMARY)
  "start/framework/installation.md"
  "start/framework/routing.md"
  "start/framework/route-module.md"
  "start/framework/rendering.md"
  "start/framework/data-loading.md"
  "start/framework/actions.md"
  "start/framework/navigating.md"
  "start/framework/pending-ui.md"
  "start/framework/deploying.md"
  "start/framework/testing.md"
  # Framework conventions
  "api/framework-conventions/routes.ts.md"
  "api/framework-conventions/root.tsx.md"
  "api/framework-conventions/react-router.config.ts.md"
  "api/framework-conventions/entry.server.tsx.md"
  "api/framework-conventions/entry.client.tsx.md"
  "api/framework-conventions/server-modules.md"
  "api/framework-conventions/client-modules.md"
  # Hooks (key)
  "api/hooks/useLoaderData.md"
  "api/hooks/useActionData.md"
  "api/hooks/useFetcher.md"
  "api/hooks/useNavigation.md"
  "api/hooks/useNavigate.md"
  "api/hooks/useParams.md"
  "api/hooks/useSearchParams.md"
  "api/hooks/useSubmit.md"
  "api/hooks/useRouteError.md"
  "api/hooks/useRevalidator.md"
  # Components (key)
  "api/components/Form.md"
  "api/components/Link.md"
  "api/components/NavLink.md"
  "api/components/Outlet.md"
  "api/components/Meta.md"
  "api/components/Links.md"
  "api/components/Scripts.md"
  "api/components/ScrollRestoration.md"
  # Utils
  "api/utils/redirect.md"
  "api/utils/redirectDocument.md"
  "api/utils/replace.md"
  "api/utils/data.md"
  "api/utils/href.md"
  "api/utils/createCookie.md"
  "api/utils/createCookieSessionStorage.md"
  "api/utils/isRouteErrorResponse.md"
  # Explanation
  "explanation/special-files.md"
  "explanation/sessions-and-cookies.md"
  "explanation/type-safety.md"
  "explanation/hydration.md"
  # How-to
  "how-to/spa.md"
  "how-to/middleware.md"
  "how-to/security.md"
  "how-to/file-route-conventions.md"
  "how-to/route-module-type-safety.md"
  "how-to/error-boundary.md"
  "how-to/headers.md"
  "how-to/meta.md"
  "how-to/pre-rendering.md"
  "how-to/status.md"
  # Upgrading
  "upgrading/remix.md"
  "upgrading/v6.md"
)

# Reset _urls.txt with a fresh header
SNAPSHOT_DATE="$(date -u +%Y-%m-%d)"
{
  echo "# React Router v7 docs mirror — pulled $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Source: https://github.com/remix-run/react-router/tree/main/docs"
  echo ""
} > "$OUT/_urls.txt"

for f in "${files[@]}"; do
  raw_url="$RAW_BASE/$f"
  slug="${f//\//__}"
  out_file="$OUT/$slug"
  if curl -fsSL "$raw_url" -o "$out_file"; then
    echo "$raw_url" >> "$OUT/_urls.txt"
  else
    echo "# 404 — dropped: $raw_url" >> "$OUT/_urls.txt"
    rm -f "$out_file"
  fi
done

# Date stamp
echo "$SNAPSHOT_DATE" > "$OUT/_snapshot_date.txt"

echo "Mirrored React Router v7 docs to $OUT"
echo "Snapshot date: $SNAPSHOT_DATE"
echo "File count: $(ls -1 "$OUT" | wc -l | tr -d ' ')"
echo "Total size: $(du -sh "$OUT" | awk '{print $1}')"
echo ""
echo "Note: reference.md (context7 dump) is NOT regenerated by this script."
echo "      See the TODO comment at the top of this file."
