#!/usr/bin/env bash
# sync-microsoft-graph-docs.sh — refresh docs/microsoft-graph/ from learn.microsoft.com
#
# Idempotent: re-runs replace files, exit 0 on success.
# Origin: https://learn.microsoft.com/en-us/graph
#
# NOTE: reference.md (context7 chunks) is NOT regenerated by this script.
#       Context7 access requires the Claude Code MCP runtime.
# TODO: regenerate reference.md by invoking mcp__context7__query-docs against
#       /microsoftgraph/microsoft-graph-docs-contrib with the same query string
#       documented at the top of reference.md, then overwrite that file.
#
# Pages are server-rendered HTML on learn.microsoft.com (content embedded
# in the initial doc, hydrated client-side after). curl gets the full doc.
# We store the raw HTML — markdown conversion would lose code-tab metadata.
# _urls.txt records origin + byte count per file for drift detection.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="${ROOT_DIR}/docs/microsoft-graph"
SNAPSHOT_DATE="2026-05-22"

mkdir -p "${OUT_DIR}"

declare -a PAGES=(
  "auth-v2-user|https://learn.microsoft.com/en-us/graph/auth-v2-user"
  "auth-concepts|https://learn.microsoft.com/en-us/graph/auth/auth-concepts"
  "api-user-sendmail|https://learn.microsoft.com/en-us/graph/api/user-sendmail"
  "api-user-list-messages|https://learn.microsoft.com/en-us/graph/api/user-list-messages"
  "webhooks|https://learn.microsoft.com/en-us/graph/change-notifications-overview"
  "subscription-post-subscriptions|https://learn.microsoft.com/en-us/graph/api/subscription-post-subscriptions"
  "api-user-list-events|https://learn.microsoft.com/en-us/graph/api/user-list-events"
  "outlook-large-attachments|https://learn.microsoft.com/en-us/graph/outlook-large-attachments"
  "throttling|https://learn.microsoft.com/en-us/graph/throttling"
  "permissions-reference|https://learn.microsoft.com/en-us/graph/permissions-reference"
)

URLS_FILE="${OUT_DIR}/_urls.txt"
{
  echo "# Microsoft Graph docs — origin URLs"
  echo "# Snapshot: ${SNAPSHOT_DATE}"
  echo "# Origin root: https://learn.microsoft.com/en-us/graph"
  echo "# Note: server-rendered HTML stored verbatim (no md conversion — would"
  echo "#       lose code-tab metadata). Byte counts below catch upstream drift."
  echo ""
} > "${URLS_FILE}"

for entry in "${PAGES[@]}"; do
  slug="${entry%%|*}"
  url="${entry#*|}"
  out_file="${OUT_DIR}/${slug}.md"
  echo "Fetching ${url}..."
  if curl -fsSL \
       -A "Mozilla/5.0 (compatible; genesisxsx-docs-sync/1.0)" \
       -o "${out_file}" \
       "${url}"; then
    size=$(wc -c <"${out_file}" | tr -d ' ')
    echo "${slug}.md  <-  ${url}  (${size} bytes)" >> "${URLS_FILE}"
  else
    echo "WARN: curl failed for ${url}" >&2
    echo "${slug}.md  <-  ${url}  (FETCH FAILED)" >> "${URLS_FILE}"
  fi
done

echo "${SNAPSHOT_DATE}" > "${OUT_DIR}/_snapshot_date.txt"

echo "Sync complete. Files in ${OUT_DIR}:"
ls -la "${OUT_DIR}"
