-- Belt-and-suspenders lockdown for purge_advisor_audit_log.
--
-- The /api/public/hooks/purge-audit-log route used to accept any non-empty
-- bearer token and then call this SECURITY DEFINER RPC. The route is now
-- gated by CRON_SECRET, but the RPC itself should also reject anon and
-- authenticated callers so that any other path into the function (direct
-- PostgREST call with an anon JWT, etc.) is denied at the database layer.
--
-- The previous lockdown migration (20260517133315) already includes this
-- function in the "server-only" group, but we re-state the REVOKE here so
-- intent is grep-able from the route file and any future GRANT regression
-- is caught by this migration's noisy failure mode.
REVOKE EXECUTE ON FUNCTION public.purge_advisor_audit_log() FROM PUBLIC, anon, authenticated;
-- service_role + the postgres owner can still execute (Supabase service-role
-- bypasses GRANTs; pg_cron runs as the function owner).
