import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogDescription,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { Wand2, Sparkles, KeyRound, Zap } from "lucide-react";
import { useAuth } from "@/components/auth/AuthProvider";
import { useAutoOutreachPreference } from "@/hooks/useAutoOutreachPreference";
import { useAutoFindLeads } from "@/hooks/useAutoFindLeads";
import { formatResetDate, nextMonthResetIso } from "@/lib/auto-find-leads-helpers";
import { AutoFindLeadsSearchForm } from "@/components/crm/AutoFindLeadsSearchForm";
import { AutoFindLeadsImportFlow } from "@/components/crm/AutoFindLeadsImportFlow";
import {
  IntegrationMissingPanel,
  CapReachedPanel,
  ImportSuccessPanel,
} from "@/components/crm/AutoFindLeadsPanels";

interface AutoFindLeadsDialogProps {
  onLeadsImported?: () => void;
  /** Optional controlled open state — used when triggered from another panel (e.g. AI Advisor). */
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  /** Hide the default "Auto-find" trigger button. Useful when controlled externally. */
  hideTrigger?: boolean;
  /** Pre-populate the search description (e.g. AI Advisor → strategic hook / ICP summary). */
  initialDescription?: string;
  /** Pre-populate the industry filter. */
  initialIndustry?: string;
}

export function AutoFindLeadsDialog({
  onLeadsImported,
  open: controlledOpen,
  onOpenChange: controlledOnOpenChange,
  hideTrigger,
  initialDescription,
  initialIndustry,
}: AutoFindLeadsDialogProps) {
  const { role } = useAuth();
  const isOwner = role?.role === "owner";
  const { enabled: outreachEnabled, setEnabled: setOutreachEnabled } = useAutoOutreachPreference();

  const [internalOpen, setInternalOpen] = useState(false);
  const isControlled = controlledOpen !== undefined;
  const open = isControlled ? controlledOpen : internalOpen;
  const setOpen = (v: boolean) => {
    if (!isControlled) setInternalOpen(v);
    controlledOnOpenChange?.(v);
  };

  const flow = useAutoFindLeads({
    open,
    initialDescription,
    initialIndustry,
    outreachEnabled,
    onLeadsImported,
  });

  const closeDialog = () => setOpen(false);

  // Show the full upgrade panel when the server returned QUOTA_EXCEEDED OR
  // the user already has zero credits left (no point letting them try).
  const isAtCap = flow.errorCode === "QUOTA_EXCEEDED" || flow.outOfCredits;
  // Show a dedicated "connect a lead source" panel when the server told us
  // no Apollo/Hunter/Snov credentials are wired up. Owner-only — non-owners
  // can't fix it, so we keep the inline error so they still see the filters.
  const needsIntegration =
    (flow.errorCode === "INTEGRATION_MISSING" || flow.errorCode === "PLATFORM_KEY_MISSING") &&
    isOwner;
  // Build a friendly message when we're showing the upgrade panel due to
  // pre-flight detection (no server error to display).
  const capMessage =
    flow.error ||
    (flow.outOfCredits
      ? `You've used all ${flow.usage?.quota} of your monthly lead credits. Upgrade your plan for more, or add your own Apollo key for unlimited.`
      : "You've hit your monthly cap.");

  return (
    <Dialog
      open={open}
      onOpenChange={(v) => {
        setOpen(v);
        if (!v) flow.reset();
      }}
    >
      {!hideTrigger && (
        <DialogTrigger asChild>
          <Button variant="command" size="sm">
            <Wand2 className="h-4 w-4" />
            Auto-Find Leads
          </Button>
        </DialogTrigger>
      )}
      <DialogContent className="sm:max-w-xl max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-primary" />
            Find Real Leads
          </DialogTitle>
          <DialogDescription>
            Verified B2B contacts pulled directly from Apollo, Hunter, or Snov — not generated by
            AI.
          </DialogDescription>
        </DialogHeader>

        {/* Quota / BYO status banner */}
        {!flow.imported && !isAtCap && flow.showQuotaBar && (
          <div className="rounded-lg border border-border bg-secondary/30 px-3 py-2.5 space-y-1.5">
            <div className="flex items-center justify-between text-xs">
              <div className="flex items-center gap-1.5 font-medium text-foreground">
                <Zap className="h-3.5 w-3.5 text-primary" />
                Monthly lead credits
              </div>
              <span className="text-muted-foreground">
                <span className="font-semibold text-foreground">{flow.usage!.used}</span> /{" "}
                {flow.usage!.quota}
              </span>
            </div>
            <Progress value={flow.quotaPct} className="h-1.5" />
            {flow.usage!.remaining < 10 && flow.usage!.remaining > 0 && (
              <p className="text-[11px] text-warning">
                Only {flow.usage!.remaining} credits left — they reset on the 1st.
              </p>
            )}
          </div>
        )}
        {!flow.imported && !isAtCap && flow.usage?.hasByoKey && (
          <div className="flex items-center gap-2 rounded-lg border border-success/30 bg-success/5 px-3 py-2 text-xs">
            <KeyRound className="h-3.5 w-3.5 text-success" />
            <span className="text-foreground font-medium">Using your own Apollo key</span>
            <span className="text-muted-foreground">— unlimited, billed by Apollo</span>
          </div>
        )}

        {needsIntegration ? (
          <IntegrationMissingPanel
            error={flow.error}
            onReset={flow.reset}
            onCloseDialog={closeDialog}
          />
        ) : isAtCap ? (
          <CapReachedPanel
            resetLabel={formatResetDate(flow.quotaResetAt || nextMonthResetIso())}
            capMessage={capMessage}
            isOwner={isOwner}
            onReset={flow.reset}
            onCloseDialog={closeDialog}
          />
        ) : flow.imported ? (
          <ImportSuccessPanel
            onFindMore={flow.reset}
            onDone={() => {
              setOpen(false);
              flow.reset();
            }}
          />
        ) : flow.suggestions.length === 0 ? (
          <AutoFindLeadsSearchForm flow={flow} isOwner={isOwner} onCloseDialog={closeDialog} />
        ) : (
          <AutoFindLeadsImportFlow
            flow={flow}
            outreachEnabled={outreachEnabled}
            onOutreachEnabledChange={setOutreachEnabled}
          />
        )}
      </DialogContent>
    </Dialog>
  );
}
